language: go
go:
  - 1.9
script:
  - go test -v ./...
  - go build
  - sha256sum monit_exporter > monit_exporter.sha256
deploy:
  provider: releases
  api_key:
    secure: ZY6L8Hq6jdIs6TP5MnNVoaqUrYxfsGVArTCOgTNtGWBD0QDYXkKuRRXZwP6c2vLaYtEtPnhQm9FuFRJKV05Xf3WotppC3CjRzfY63jZtKC8DD38HAqUFL9DEBn8kwTWQKRLVN4gYFGAWidCOTJfMEnuowpptnvfzTQyR4zNxCWfmKue3nDNGzTs3almLFCAODC94jqFdSmQHyL9/7uWqBxOGZWGleNK6t1w7x9ah+XBPZNp4nMiP9fXXX+NGuf+wmxQKYCF2xyadClxoIEIwb4FAsHhKgwDPo5cS49TAqKBD2gViDNIKnf2+OBkjMvxUBxWLUCleVJjqHdz/UJSF+Wkh/ODFRysrbPmPmDaeqrE8TprnoP8CFlKO91YYaiR6qgukL9o2w7kq++vrPk0DgqvnqqYdPkg8WHvGNEczm5lq2y9Wf6yIZYTJVsZSFiPUHtPfINFFiTNLxekfNqTYw/jt7zWxUQjry/Low4CqIAVUYfgEaPuXK6bWYu83XMf2R/0X38lzknlqw9sjJAddUn/Q0XIJV1+53XD1qmaVR8qUnHBHWCt5S8I50hj8eZrGHX3pCVERInpPaNmBRBaQBqFQ86nP3waRD+z8hnLU21zVWtVGucvwYv3iaOmV4HlGCmvcgHjElGhylkA42PR/tCwFrhwHtKeXVJOvcuaoU+s=
  file:
    - monit_exporter
    - monit_exporter.sha256
  skip_cleanup: true
  on:
    public_repo: commercetools/monit_exporter
    tags: true
